### PR TITLE
Updated the readme

### PR DESCRIPTION
**Pull request by AshM10**

### CODE REVIEW

**Comment by AshM10** [comment]
Hi, this is the readme draft. 

Will be able to finish this once the project is done but this can be merged with MAIN. 
Please review, thanks! ❤️

**Review by princemuel — APPROVED** [review]
This is great.

**Comment by JoleneKearse** [comment]
Looks good!

**Review by JoleneKearse — APPROVED** [review]

**Comment by JoleneKearse** [comment]
Closed

**Pull request closed without merging**
